###########################
#
#  Tag Configuration options
#
###########################
[tag]
	menu = [
	  "|fmt",
	  "|com",
	  "|a-",
	  "|a+",
	  "Ldef",
	  "Lrefs",
	  "Lcomp",
	  "win"
	]

###########################
#
#  Buffer Formatting Options
#
###########################
[format]
	# This will automatically format Go buffers with hard tabs and 8
	# character width indentation
	[format.go]
	extensions = [".go"]
	indent = 8
	tabexpand = false
	commentstyle = "// "
	
		# run gofmt on save
		[[format.go.commands]]
		exec = "gofmt"
		args = [ "$NAME" ]
		
		# if the command you want to run does not print to stdout,
		# set this to false
		printsToStdout = true
	
	[format.c]
	extensions = [".c", ".h"]
	indent = 8
	tabexpand = false
	commentstyle = "/* */"

		[[format.c.commands]]
		exec = "indent"
		args = [
			"-st",
			"-bap",
			"-bli0",
			"-i4",
			"-l79",
			"-ncs",
			"-npcs",
			"-npsl",
			"-fca",
			"-lc79",
			"-fc1",
			"-ts4",
			"$NAME"
		]
		printsToStdout = true
	
	[format.cpp]
	extensions = [".cc", ".cpp", ".hpp", ".cxx", ".hxx"]
	indent = 2
	tabexpand = true
	commentstyle = "// "

	[format.js]
	extensions = [".js"]
	indent = 2
	tabexpand = true
	commentstyle = "// "
	
		[[format.js.commands]]
		exec = "prettier"
		args = [ "$NAME", "--write", "--loglevel", "error" ]
		printsToStdout = false

	[format.make]
	extensions = ["Makefile"]
	indent = 8
	tabexpand = false
	commentstyle = "# "
	
	[format.shell]
	extensions = [".rc", ".sh"]
	indent = 8
	tabexpand = false
	commentstyle = "# "

	[format.tf]
	extensions = [".tf"]
	indent = 2
	tabexpand = true
	commentstyle = "# "
	
		[[format.tf.commands]]
		exec = "terraform"
		args = [ "fmt", "$NAME"]
		printsToStdout = false

	[format.html]
	extensions = [".html"]
	indent = 2
	tabexpand = true
	commentstyle = "<!-- -->"

	[format.java]
	extensions = [".java"]
	indent = 2
	tabexpand = true
	commentstyle = "// "
	
		[[format.java.commands]]
		exec = "google-java-format"
		args = [ "$NAME" ]
		printsToStdout = true

	[format.yaml]
	extensions = [".yml", ".yaml"]
	indent = 2
	tabexpand = true
	commentstyle = "# "

	[format.json]
	extensions = [".json"]
	indent = 2
	tabexpand = true

	[format.markdown]
	extensions = [".md"]
	indent = 2
	tabexpand = true
	
		[[format.markdown.commands]]
		exec = "prettier"
		args = [ 
			"--print-width", "80", 
			"--prose-wrap", "always", 
			"--write", "$NAME",
		]
		printsToStdout = false	

	[format.toml]
	extensions = [".toml"]
	indent = 8
	tabexpand = false
	commentstyle = "# "
